//
//  AGGREGATE.H
//  Q3Q4a1_comp348
//
//  Created by Maria Ghobrial on 2022-05-13.
//

#ifndef AGGREGATE_h
#define AGGREGATE_h
float min(float arr[], int size);
float max(float arr[], int size);
float sum(float arr[], int size);
float avg(float arr[], int size);
float pseudo_avg(float arr[], int size);
//float (*aggregates[5])(float arr[], int size) = {min, max, sum, avg, pseudo_avg}; //gives a duplicate symbol error


#endif /* AGGREGATE_h */
